# Generated by Django 2.1 on 2019-04-03 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190403_2207'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': ('アイテム',), 'verbose_name_plural': ('アイテム',)},
        ),
    ]
